<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'codegenerator' => '/CodeGenerator.php',
                'lottery' => '/Lottery.php',
                'onethousandwinamountstrategy' => '/OneThousandWinAmountStrategy.php',
                'ticket' => '/Ticket.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
